USE SCHEMA CRICKET.CONSUMPTION;

-- 1. Dimension Table Creation
-- DATE DIM (Simplified - Assumes external tool or script for full population)
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID         NUMBER PRIMARY KEY,
    FULL_DATE       DATE NOT NULL,
    DATE_YEAR       NUMBER,
    DATE_MONTH      NUMBER,
    DATE_DAY        NUMBER
);

-- TEAM DIMENSION
CREATE OR REPLACE TABLE DIM_TEAM (
    TEAM_ID         NUMBER IDENTITY(1,1) PRIMARY KEY,
    TEAM_NAME       VARCHAR(100) NOT NULL UNIQUE
);

-- PLAYER DIMENSION
CREATE OR REPLACE TABLE DIM_PLAYER (
    PLAYER_ID       NUMBER IDENTITY(1,1) PRIMARY KEY,
    TEAM_ID         NUMBER REFERENCES DIM_TEAM(TEAM_ID),
    PLAYER_NAME     VARCHAR(255) NOT NULL
);

-- VENUE DIMENSION
CREATE OR REPLACE TABLE DIM_VENUE (
    VENUE_ID        NUMBER IDENTITY(1,1) PRIMARY KEY,
    VENUE_NAME      VARCHAR(255) NOT NULL,
    CITY            VARCHAR(255)
);

-- 2. Population (ETL from Clean Layer)

-- Populate DIM_TEAM
INSERT INTO DIM_TEAM (TEAM_NAME)
SELECT DISTINCT TEAM_A AS TEAM_NAME FROM CRICKET.CLEAN.MATCH_DETAIL_CLEAN
UNION
SELECT DISTINCT TEAM_B AS TEAM_NAME FROM CRICKET.CLEAN.MATCH_DETAIL_CLEAN;

-- Populate DIM_VENUE
INSERT INTO DIM_VENUE (VENUE_NAME, CITY)
SELECT
    DISTINCT VENUE AS VENUE_NAME,
    COALESCE(CITY, 'N/A') AS CITY
FROM CRICKET.CLEAN.MATCH_DETAIL_CLEAN;

-- Populate DIM_PLAYER (Requires join to get TEAM_ID)
INSERT INTO DIM_PLAYER (TEAM_ID, PLAYER_NAME)
SELECT
    T.TEAM_ID,
    P.PLAYER_NAME
FROM CRICKET.CLEAN.PLAYER_CLEAN P
INNER JOIN CRICKET.CONSUMPTION.DIM_TEAM T ON P.COUNTRY = T.TEAM_NAME
GROUP BY 1, 2;
