USE SCHEMA CRICKET.CONSUMPTION;

-- 1. Dimension Table Creation
-- DATE DIM (Simplified - Assumes external tool or script for full population)
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID         NUMBER PRIMARY KEY,
    FULL_DATE       DATE NOT NULL,
    DATE_YEAR       NUMBER,
    DATE_MONTH      NUMBER,
    DATE_DAY        NUMBER
);

-- TEAM DIMENSION
CREATE OR REPLACE TABLE DIM_TEAM (
    TEAM_ID         NUMBER IDENTITY(1,1) PRIMARY KEY,
    TEAM_NAME       VARCHAR(100) NOT NULL UNIQUE
);

-- PLAYER DIMENSION
CREATE OR REPLACE TABLE DIM_PLAYER (
    PLAYER_ID       NUMBER IDENTITY(1,1) PRIMARY KEY,
    TEAM_ID         NUMBER REFERENCES DIM_TEAM(TEAM_ID),
    PLAYER_NAME     VARCHAR(255) NOT NULL
);

-- VENUE DIMENSION
CREATE OR REPLACE TABLE DIM_VENUE (
    VENUE_ID        NUMBER IDENTITY(1,1) PRIMARY KEY,
    VENUE_NAME      VARCHAR(255) NOT NULL,
    CITY            VARCHAR(255)
);

-- 2. Population (ETL from Clean Layer)

-- Populate DIM_TEAM
INSERT INTO DIM_TEAM (TEAM_NAME)
SELECT DISTINCT TEAM_A AS TEAM_NAME FROM CRICKET.CLEAN.MATCH_DETAIL_CLEAN
UNION
SELECT DISTINCT TEAM_B AS TEAM_NAME FROM CRICKET.CLEAN.MATCH_DETAIL_CLEAN;

-- Populate DIM_VENUE
INSERT INTO DIM_VENUE (VENUE_NAME, CITY)
SELECT
    DISTINCT VENUE AS VENUE_NAME,
    COALESCE(CITY, 'N/A') AS CITY
FROM CRICKET.CLEAN.MATCH_DETAIL_CLEAN;

-- Populate DIM_PLAYER (Requires join to get TEAM_ID)
INSERT INTO DIM_PLAYER (TEAM_ID, PLAYER_NAME)
SELECT
    T.TEAM_ID,
    P.PLAYER_NAME
FROM CRICKET.CLEAN.PLAYER_CLEAN P
INNER JOIN CRICKET.CONSUMPTION.DIM_TEAM T ON P.COUNTRY = T.TEAM_NAME
GROUP BY 1, 2;



USE SCHEMA CRICKET.CONSUMPTION;

-- 1. Match Fact Table (One row per match event)
CREATE OR REPLACE TABLE FACT_MATCH (
    MATCH_KEY            NUMBER IDENTITY(1,1) PRIMARY KEY,
    MATCH_TYPE_NUMBER    NUMBER, -- Natural Key
    -- Foreign Keys
    DATE_ID              NUMBER REFERENCES DIM_DATE(DATE_ID),
    VENUE_ID             NUMBER REFERENCES DIM_VENUE(VENUE_ID),
    TEAM_A_ID            NUMBER REFERENCES DIM_TEAM(TEAM_ID),
    TEAM_B_ID            NUMBER REFERENCES DIM_TEAM(TEAM_ID),
    WINNER_TEAM_ID       NUMBER REFERENCES DIM_TEAM(TEAM_ID),
    TOSS_WINNER_ID       NUMBER REFERENCES DIM_TEAM(TEAM_ID),
    -- Measures & Attributes
    MATCH_STAGE          VARCHAR(50),
    TOTAL_OVERS          NUMBER,
    TEAM_A_TOTAL_SCORE   NUMBER,
    TEAM_B_TOTAL_SCORE   NUMBER,
    TEAM_A_WICKETS       NUMBER,
    TEAM_B_WICKETS       NUMBER,
    MATCH_RESULT_STATUS  VARCHAR(50)
);

-- 2. Delivery Fact Table (One row per ball/delivery)
CREATE OR REPLACE TABLE FACT_DELIVERY (
    DELIVERY_KEY        NUMBER IDENTITY(1,1) PRIMARY KEY,
    MATCH_KEY           NUMBER REFERENCES FACT_MATCH(MATCH_KEY), -- Link to Match Fact
    INNINGS_NUMBER      NUMBER,
    OVER_NUMBER         NUMBER,
    BALL_NUMBER         NUMBER,
    -- Foreign Keys for Players
    TEAM_ID             NUMBER REFERENCES DIM_TEAM(TEAM_ID),
    BOWLER_ID           NUMBER REFERENCES DIM_PLAYER(PLAYER_ID),
    BATTER_ID           NUMBER REFERENCES DIM_PLAYER(PLAYER_ID),
    NON_STRIKER_ID      NUMBER REFERENCES DIM_PLAYER(PLAYER_ID),
    -- Measures
    RUNS_SCORED_BATTER  NUMBER,
    RUNS_SCORED_EXTRA   NUMBER,
    RUNS_SCORED_TOTAL   NUMBER,
    WICKET_KIND_OF_OUT  VARCHAR(50)
);

-- 3. Population (Example FACT_DELIVERY)
INSERT INTO FACT_DELIVERY (
    MATCH_KEY, INNINGS_NUMBER, OVER_NUMBER, BALL_NUMBER,
    TEAM_ID, BOWLER_ID, BATTER_ID, NON_STRIKER_ID,
    RUNS_SCORED_BATTER, RUNS_SCORED_EXTRA, RUNS_SCORED_TOTAL, WICKET_KIND_OF_OUT
)
SELECT
    FM.MATCH_KEY,
    DC.INNINGS_NUMBER,
    DC.OVER_NUMBER,
    DC.BALL_NUMBER,
    T.TEAM_ID,
    PB.PLAYER_ID AS BOWLER_ID,
    PA.PLAYER_ID AS BATTER_ID,
    PN.PLAYER_ID AS NON_STRIKER_ID,
    DC.RUNS_SCORED_BATTER,
    DC.RUNS_SCORED_EXTRA,
    DC.RUNS_SCORED_TOTAL,
    DC.WICKET_KIND_OF_OUT
FROM CRICKET.CLEAN.DELIVERY_CLEAN DC
INNER JOIN CRICKET.CONSUMPTION.DIM_TEAM T ON DC.INNINGS_TEAM_NAME = T.TEAM_NAME
INNER JOIN CRICKET.CONSUMPTION.FACT_MATCH FM ON DC.MATCH_TYPE_NUMBER = FM.MATCH_TYPE_NUMBER
LEFT JOIN CRICKET.CONSUMPTION.DIM_PLAYER PB ON DC.BOWLER_NAME = PB.PLAYER_NAME -- Bowler
LEFT JOIN CRICKET.CONSUMPTION.DIM_PLAYER PA ON DC.BATTER_NAME = PA.PLAYER_NAME  -- Batter
LEFT JOIN CRICKET.CONSUMPTION.DIM_PLAYER PN ON DC.NON_STRIKER_NAME = PN.PLAYER_NAME; -- Non-Striker
