USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

-- A. Create Streams on the Raw Table to track new data
-- Note: Streams are Append-Only because the data source is only new files (COPY INTO)
CREATE OR REPLACE STREAM CRICKET.RAW.MATCH_S_STREAM ON CRICKET.RAW.MATCH_RAW_TBL APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM CRICKET.RAW.PLAYER_S_STREAM ON CRICKET.RAW.MATCH_RAW_TBL APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM CRICKET.RAW.DELIVERY_S_STREAM ON CRICKET.RAW.MATCH_RAW_TBL APPEND_ONLY = TRUE;

-- B. Task Definitions (Illustrative DAG - Task dependencies are added in the DDL)

-- 1. PARENT: Task to load new data into Clean Tables (Runs when Stream has data)
CREATE OR REPLACE TASK LOAD_CLEAN_MATCH_TASK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('CRICKET.RAW.MATCH_S_STREAM')
AS
INSERT INTO CRICKET.CLEAN.MATCH_DETAIL_CLEAN (...)
SELECT ... FROM CRICKET.RAW.MATCH_S_STREAM; -- Use Stream as source to get Delta

-- 2. CHILD 1: Load Dimension Tables (Runs AFTER Clean Match is done)
CREATE OR REPLACE TASK LOAD_DIM_TEAM_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER LOAD_CLEAN_MATCH_TASK
AS
INSERT INTO CRICKET.CONSUMPTION.DIM_TEAM (TEAM_NAME)
SELECT DISTINCT TEAM_A AS TEAM_NAME FROM CRICKET.CLEAN.MATCH_DETAIL_CLEAN -- Use the base table for full set
WHERE TEAM_NAME NOT IN (SELECT TEAM_NAME FROM CRICKET.CONSUMPTION.DIM_TEAM); -- Incremental population logic

-- 3. CHILD 2: Load Fact Table (Runs AFTER Dimensions are ready)
CREATE OR REPLACE TASK LOAD_FACT_MATCH_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER LOAD_DIM_TEAM_TASK
AS
INSERT INTO CRICKET.CONSUMPTION.FACT_MATCH (...)
SELECT ... FROM CRICKET.CLEAN.MATCH_DETAIL_CLEAN C
LEFT JOIN CRICKET.CONSUMPTION.FACT_MATCH F
ON C.MATCH_TYPE_NUMBER = F.MATCH_TYPE_NUMBER
WHERE F.MATCH_TYPE_NUMBER IS NULL; -- Logic to only insert new matches
